# Generated by Django 2.2.1 on 2019-10-22 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20191012_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='searchurl',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
