# Generated by Django 2.2.1 on 2019-10-22 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20191022_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='searchtitle',
            field=models.CharField(max_length=255),
        ),
    ]
