# Generated by Django 2.2.1 on 2019-11-06 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20191022_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='searchurl',
            field=models.CharField(blank=True, default='null', max_length=128),
        ),
    ]
