# Generated by Django 2.2.1 on 2019-11-08 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20191106_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='headimg',
            field=models.ImageField(blank=True, upload_to='headimg'),
        ),
    ]
