# Generated by Django 2.2.1 on 2019-11-12 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20191108_1403'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hot_search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hot_searchtitle', models.CharField(max_length=255)),
                ('Hot_searchurl', models.CharField(blank=True, default='null', max_length=128)),
                ('Hot_searchtime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
