# Generated by Django 2.2.1 on 2020-03-24 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_hot_search'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProxyIp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=125)),
                ('port', models.CharField(max_length=125)),
                ('category', models.CharField(max_length=125)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='description',
        ),
        migrations.RemoveField(
            model_name='user',
            name='job',
        ),
        migrations.AlterField(
            model_name='user',
            name='headimg',
            field=models.ImageField(blank=True, default='media/head.jpg', upload_to='headimg'),
        ),
    ]
